### ISSUE TITLE
Support path pattern parameter

### ISSUE THREAD

**Issue by morazow** [itsallcode/openfasttrace-maven-plugin#12]
### Situation

OFT looks for the tags inside the [supported file extensions](https://github.com/itsallcode/openfasttrace/blob/develop/importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/TagImporterFactory.java#L42-L62). Usually, for the non Java sources with these extension, you could use [`build-helper-maven-plugin`](https://www.mojohaus.org/build-helper-maven-plugin/usage.html) to add additional sources. For example, Lua sources.

For other file extension which are not in the supported list, OFT provides pattern (both regex, glob) API. It would be helpful if this plugin also supports it.

### Expected Solution

For example, for Scala sources src/main/scala, I would like to define a `pathPattern` as below:

```xml
<plugin>
    <groupId>org.itsallcode</groupId>
    <artifactId>openfasttrace-maven-plugin</artifactId>
    <version>1.0.1</version>
    <executions>
        <execution>
            <id>trace-requirements</id>
            <goals>
                <goal>trace</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <reportOutputFormat>html</reportOutputFormat>
        <reportVerbosity>ALL</reportVerbosity>
        <reportShowOrigin>true</reportShowOrigin>
        <pathPattern>**.scala</pathPattern>
    </configuration>
</plugin>
```

`pathPattern` is initial suggestion, we could change it to `pathConfigPattern` or other nice descriptive parameter name.

### Alternative Solution

Another solution would be to add user additional file extensions to the supported list and do release of oft and oft-maven plugins.

**Comment by morazow** [comment]
I would be happy to send a pull request for this.

**Comment by kaklakariada** [comment]
Thank you for your feature request and your offer to implement this! And sorry for the late reply :-/

I am not a Maven expert, but maybe your use case is already covered. The plugin already adds the following to the list of input directories:

* `project.getCompileSourceRoots()`
* `project.getTestCompileSourceRoots()`

See [TraceMojo.java#L190](https://github.com/itsallcode/openfasttrace-maven-plugin/blob/42c46ca5729a6080ef5b7e3ca626c8ee083d3bbb/src/main/java/org/itsallcode/openfasttrace/maven/TraceMojo.java#L190).

I don't know if this considers paths added via `build-helper-maven-plugin`. This would be my favorite solution, because it's automatic an requires no additional configuration. But if it's not possible, I would be happy to accept your pull request :)

**Comment by kaklakariada** [comment]
I agree. As you said this is a conflict with how OFTs finds the correct `ImporterFactory`.
One option would be to allow configuration of a mapping between globs and importers -- maybe only via API, not CLI. Then we can make this configuration accessible via the Maven and Gradle plugins.
@redcatbear: What do you think?
